server:
  port: 18085

spring:
  application:
    name: api-product
  data:
    mongodb:
      uri: mongodb://localhost:27017/Bank
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
