server:
  port: 18085
  
spring:
  data:
    application:
      name: product
    mongodb:
      uri: mongodb://localhost:27017/Bank
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
