server:
  port: 18082

spring:
  application:
    name: api-passive
  data:
    mongodb:
      uri: mongodb://localhost:27017/Bank
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka