server:
  port: 18082

spring:
  application:
    name: api-passive
  data:
    mongodb:
      uri: mongodb://localhost:27017/Bank
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#circuitbreaker ---
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ClientCompany:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 5
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true