server:
  port: 28088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-product
          uri: http://localhost:18085/
          #uri: lb://api-product1
          predicates:
            - Path=/v1/products/**